<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Feature', 'echelon-fse' ),
	'categories' => array( 'echelon-fse-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"gap":"no","elementId":"guten-UIp4XJ","margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":"10","left":"10"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-3ZG86u","background":{"type":"default","color":{"type":"variable","id":"gv-color-background-tertiary"}},"border":{"radius":{"Desktop":[]}},"boxShadow":{"color":{"r":9,"g":31,"b":52,"a":0.1},"vertical":"5","blur":"25"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-155","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":"60"}},"Tablet":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0"}}}} -->
<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-SL87yB","margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":24,"Tablet":50,"Mobile":null},"elementId":"guten-A2PLDf","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"20","bottom":"40","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20"}}}} -->
<!-- wp:gutenverse/icon-box {"elementId":"guten-j3hktI","title":"Business Grow","description":"Lorem ipsum dolor sit amet consecte turadipiscing elit sed do eiusmodte","iconType":"none","iconPosition":"top","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"12","left":"0"}},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"gv-color-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-feature-secondary"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"60","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0"}},"Mobile":[]},"descColor":{"type":"variable","id":"gv-color-text-secondary"},"descTypography":{"type":"variable","id":"gv-font-text"},"badgePadding":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeIn"},"duration":"normal","delay":"300"},"parentSelector":".guten-j3hktI:hover .guten-icon-box-wrapper","hasInnerBlocks":true,"imageLoad":"eager"} -->
<!-- wp:gutenverse/button {"elementId":"guten-c7Dba8","content":"Read More","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"2","right":"2","bottom":"2","left":"2"}}},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"buttonBorder":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"gtn gtn-right-arrow1-light","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0yMS41NjMgNS4wOTRxLTAuMzQ0LTAuMzQ0LTAuODEzLTAuMzQ0dC0wLjgxMyAwLjM0NHEtMC4zNDQgMC4zMTMtMC4zNDQgMC43ODF0MC4zNDQgMC44MTNsOC4xODggOC4xODhoLTI3cS0wLjQ2OSAwLTAuNzk3IDAuMzI4dC0wLjMyOCAwLjc5NyAwLjMyOCAwLjc5NyAwLjc5NyAwLjMyOGgyN2wtOC4xODggOC4xODhxLTAuMzQ0IDAuMzEzLTAuMzQ0IDAuNzk3dDAuMzQ0IDAuNzk3cTAuMzQ0IDAuMzQ0IDAuODEzIDAuMzQ0dDAuODEzLTAuMzQ0bDEwLjA5NC0xMC4wOTRxMC4zNDQtMC4zNDQgMC4zNDQtMC44MTN0LTAuMzQ0LTAuODEzbC0xMC4wOTQtMTAuMDk0eiI+PC9wYXRoPgo8L3N2Zz4K","iconPosition":"after","iconSpacing":{"Desktop":"8"},"iconSize":{"Desktop":{"point":"15","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"gv-color-primary"},"iconColor":{"type":"variable","id":"gv-color-primary"},"typography":{"type":"variable","id":"gv-font-button-secondary"},"parentSelector":".guten-j3hktI:hover .guten-icon-box-wrapper"} /-->
<!-- /wp:gutenverse/icon-box -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":24,"Tablet":50},"elementId":"guten-skVCrl","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10","top":"40","bottom":"40"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"","bottom":""}}}} -->
<!-- wp:gutenverse/icon-box {"elementId":"guten-pZsMky","title":"Media Connection","titleTag":"h3","description":"Lorem ipsum dolor sit amet consecte turadipiscing elit sed do eiusmodte","iconType":"none","iconPosition":"top","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none"}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"12","left":"0"}},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"gv-color-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-feature-secondary"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"60","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0"}},"Mobile":[]},"descColor":{"type":"variable","id":"gv-color-text-secondary"},"descTypography":{"type":"variable","id":"gv-font-text"},"badgePadding":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeIn"},"duration":"normal","delay":"500"},"parentSelector":".guten-pZsMky:hover .guten-icon-box-wrapper","hasInnerBlocks":true,"imageLoad":"eager"} -->
<!-- wp:gutenverse/button {"elementId":"guten-xa10so","content":"Read More","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"2","right":"2","bottom":"2","left":"2"}}},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"buttonBorder":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"gtn gtn-right-arrow1-light","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0yMS41NjMgNS4wOTRxLTAuMzQ0LTAuMzQ0LTAuODEzLTAuMzQ0dC0wLjgxMyAwLjM0NHEtMC4zNDQgMC4zMTMtMC4zNDQgMC43ODF0MC4zNDQgMC44MTNsOC4xODggOC4xODhoLTI3cS0wLjQ2OSAwLTAuNzk3IDAuMzI4dC0wLjMyOCAwLjc5NyAwLjMyOCAwLjc5NyAwLjc5NyAwLjMyOGgyN2wtOC4xODggOC4xODhxLTAuMzQ0IDAuMzEzLTAuMzQ0IDAuNzk3dDAuMzQ0IDAuNzk3cTAuMzQ0IDAuMzQ0IDAuODEzIDAuMzQ0dDAuODEzLTAuMzQ0bDEwLjA5NC0xMC4wOTRxMC4zNDQtMC4zNDQgMC4zNDQtMC44MTN0LTAuMzQ0LTAuODEzbC0xMC4wOTQtMTAuMDk0eiI+PC9wYXRoPgo8L3N2Zz4K","iconPosition":"after","iconSpacing":{"Desktop":"8"},"iconSize":{"Desktop":{"point":"15","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"gv-color-primary"},"iconColor":{"type":"variable","id":"gv-color-primary"},"typography":{"type":"variable","id":"gv-font-button-secondary"},"parentSelector":".guten-pZsMky:hover .guten-icon-box-wrapper"} /-->
<!-- /wp:gutenverse/icon-box -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":24,"Tablet":50,"Mobile":null},"elementId":"guten-qIw7qq","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"40","left":"20"}},"Tablet":{"unit":"px","dimension":{"left":"20","top":"","right":"20","bottom":""}},"Mobile":[]}} -->
<!-- wp:gutenverse/icon-box {"elementId":"guten-vtIvPB","title":"Smart Solution","titleTag":"h3","description":"Lorem ipsum dolor sit amet consecte turadipiscing elit sed do eiusmodte","iconType":"none","iconPosition":"top","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none"}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"12","left":"0"}},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"gv-color-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-feature-secondary"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"60","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0"}},"Mobile":[]},"descColor":{"type":"variable","id":"gv-color-text-secondary"},"descTypography":{"type":"variable","id":"gv-font-text"},"badgePadding":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeIn"},"duration":"normal","delay":"700"},"parentSelector":".guten-vtIvPB:hover .guten-icon-box-wrapper","hasInnerBlocks":true,"imageLoad":"eager"} -->
<!-- wp:gutenverse/button {"elementId":"guten-z5hYxe","content":"Read More","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"2","right":"2","bottom":"2","left":"2"}}},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"buttonBorder":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"gtn gtn-right-arrow1-light","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0yMS41NjMgNS4wOTRxLTAuMzQ0LTAuMzQ0LTAuODEzLTAuMzQ0dC0wLjgxMyAwLjM0NHEtMC4zNDQgMC4zMTMtMC4zNDQgMC43ODF0MC4zNDQgMC44MTNsOC4xODggOC4xODhoLTI3cS0wLjQ2OSAwLTAuNzk3IDAuMzI4dC0wLjMyOCAwLjc5NyAwLjMyOCAwLjc5NyAwLjc5NyAwLjMyOGgyN2wtOC4xODggOC4xODhxLTAuMzQ0IDAuMzEzLTAuMzQ0IDAuNzk3dDAuMzQ0IDAuNzk3cTAuMzQ0IDAuMzQ0IDAuODEzIDAuMzQ0dDAuODEzLTAuMzQ0bDEwLjA5NC0xMC4wOTRxMC4zNDQtMC4zNDQgMC4zNDQtMC44MTN0LTAuMzQ0LTAuODEzbC0xMC4wOTQtMTAuMDk0eiI+PC9wYXRoPgo8L3N2Zz4K","iconPosition":"after","iconSpacing":{"Desktop":"8"},"iconSize":{"Desktop":{"point":"15","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"gv-color-primary"},"iconColor":{"type":"variable","id":"gv-color-primary"},"typography":{"type":"variable","id":"gv-font-button-secondary"},"parentSelector":".guten-vtIvPB:hover .guten-icon-box-wrapper"} /-->
<!-- /wp:gutenverse/icon-box -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":28,"Tablet":50},"elementId":"guten-RvxBFi","background":{"type":"default","image":{"Desktop":{"id":1247,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/StockSnap_7BQNRHB6EX.webp"}},"position":{"Desktop":"top center"},"size":{"Desktop":"cover"}},"verticalAlign":{"Desktop":"flex-end","Tablet":"flex-end"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-65","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]}} -->
<!-- wp:gutenverse/spacer {"elementId":"guten-7qE7Eb","space":{"Desktop":{"point":"230","unit":"px"},"Tablet":{"point":"139","unit":"px"},"Mobile":{"point":"195","unit":"px"}},"margin":{"Tablet":[]},"padding":{"Tablet":[]}} /-->

<!-- wp:gutenverse/icon {"elementId":"guten-Ze1sIg","icon":"gtn gtn-play-button","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0yLjI4NiAwbDI3LjQyOSAxNi0yNy40MjkgMTZ6Ij48L3BhdGg+Cjwvc3ZnPgo=","iconAlign":{"Desktop":"right"},"ariaLabel":"play video","iconColorOne":{"type":"variable","id":"gv-color-primary"},"iconSize":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"point":"18","unit":"px"}},"iconPadding":{"Mobile":"18"},"iconColorTwo":{"type":"variable","id":"gv-color-background-tertiary"},"iconColorHoverOne":{"type":"variable","id":"gv-color-accent-hover"},"iconColorHoverTwo":{"type":"variable","id":"gv-color-background-tertiary"},"iconShape":"square","url":"#","animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"700"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":[]}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
