<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Article', 'echelon-fse' ),
	'categories' => array( 'echelon-fse-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"gap":"no","elementId":"guten-WmZHQ9","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"120","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10","top":"80","bottom":"120"}},"Mobile":{"unit":"px","dimension":{"top":"70","bottom":"120"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-WN9Sfz"} -->
<!-- wp:gutenverse/heading {"elementId":"guten-dd0E5T","content":"Latest News","type":3,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"gv-color-accent"},"typography":{"type":"variable","id":"gv-font-subheading"},"containsAnchorTag":false} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-JMsrEr","content":"Our News \u0026 Article","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-secondary"},"containsAnchorTag":false} /-->

<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-9CIamD","margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":""}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":70,"Tablet":100,"Mobile":null},"elementId":"guten-BGz1PU","animation":{"type":{"Desktop":"none"},"duration":"slow"}} -->
<!-- wp:gutenverse/post-block {"elementId":"guten-1yNE11","numberPost":"2","column":{"Desktop":"2","Mobile":"1"},"sortBy":"latest","categoryPosition":"left","excerptLength":"13","readmoreEnabled":false,"metaAuthorEnabled":false,"metaDateIconType":"svg","postblockType":"type-3","postItemGap":{"Desktop":"30","Tablet":"20"},"postItemMargin":{"Mobile":{"unit":"px","dimension":{"bottom":"5"}},"Tablet":[],"Desktop":[]},"postItemPadding":{"Mobile":[],"Desktop":[]},"postItemBorder":{"radius":{"Mobile":[],"Desktop":[]}},"thumbnailWidth":{"Desktop":""},"thumbnailMargin":{"Desktop":[]},"thumbnailPadding":{"Desktop":[]},"thumbnailBorder":{"radius":{"Desktop":[]}},"thumbnailHeight":{"Desktop":"270"},"thumbnailRadius":{"Desktop":[]},"contentMargin":{"Desktop":[]},"contentPadding":{"Desktop":[]},"contentBorder":{"radius":{"Desktop":[]}},"categoryColor":{"type":"variable","id":"gv-color-background-tertiary"},"categoryTypography":{"type":"variable","id":"gv-font-text-small"},"categoryBackground":{"type":"variable","id":"gv-color-primary"},"categoryMargin":{"Desktop":[]},"categoryPadding":{"Desktop":{"unit":"px","dimension":{"top":"12","right":"16","bottom":"12","left":"16"}},"Tablet":[]},"categoryBorder":{"radius":{"Desktop":[]}},"titleMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"gv-color-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-feature-secondary"},"excerptMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"excerptColor":{"type":"variable","id":"gv-color-text-secondary"},"excerptTypography":{"type":"variable","id":"gv-font-text"},"readmoreMargin":{"Desktop":[]},"readmorePadding":{"Desktop":[]},"readmoreIconSize":{"Desktop":{"unit":"px"}},"readmoreWidth":{"Desktop":{"unit":"px"}},"readmoreBorder":{"radius":{"Desktop":[]}},"metaTypography":{"type":"variable","id":"gv-font-text-small","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"weight":"400","lineHeight":{"Desktop":{"unit":"px"}}},"metaColor":{"type":"variable","id":"gv-color-text-placeholder"},"metaMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"metaDateIconSpacing":{"Desktop":"8"},"imageLoad":"lazy","animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""}} -->
<div class="guten-element guten-post-block guten-1yNE11"></div>
<!-- /wp:gutenverse/post-block -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":30,"Tablet":100,"Mobile":null},"elementId":"guten-oliP7V","margin":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"40","top":"-12","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"left":""}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"animation":{"type":{"Desktop":"none"},"duration":"slow"}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-HNlWsh","content":"Recent News","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-feature","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"26"},"Tablet":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"containsAnchorTag":false} /-->

<!-- wp:gutenverse/divider {"elementId":"guten-QeMDP7","width":{"Desktop":"100"},"dividerColor":{"type":"variable","id":"gv-color-border-input"},"size":{"Desktop":"1.2"},"gap":{"Desktop":"1"},"border":{"radius":{"Desktop":[]}}} /-->

<!-- wp:gutenverse/post-list {"elementId":"guten-qCgBEX","numberPost":"3","postOffset":"0","sortBy":"latest","metaEnabled":true,"metaDateEnabled":true,"metaDateIconType":"svg","metaPosition":"bottom","imageLoad":"lazy","contentMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"20","left":""}}},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"contentWidth":{"Desktop":{"point":"","unit":"px"}},"contentBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[],"Tablet":[]},"titleColor":{"type":"variable","id":"gv-color-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-text-secondary"},"metaTypography":{"type":"variable","id":"gv-font-text-small"},"metaIconSize":{"Desktop":"14"},"metaIconSpacing":{"Desktop":"6"},"metaMargin":{"Desktop":{"unit":"px","dimension":{"top":"6","bottom":""}}},"metaPadding":{"Desktop":{"unit":"px","dimension":{"bottom":""}}},"metaColor":{"type":"variable","id":"gv-color-text-placeholder"},"metaBorder":{"radius":{"Desktop":[]}},"metaHoverBorder":{"radius":{"Desktop":[]}},"paginationTypography":{"font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"15","unit":"px"}},"weight":"400"},"paginationMargin":{"Desktop":{"unit":"px","dimension":{"top":"10"}}},"paginationPadding":{"Desktop":{"unit":"px","dimension":{"top":"16","bottom":"16","right":"30","left":"30"}}},"paginationWidth":{"Desktop":"100"},"paginationColor":{"r":255,"g":255,"b":255,"a":1},"paginationBackground":{"type":"default","color":{"r":17,"g":86,"b":155,"a":1}},"paginationBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none"}},"paginationShadow":{"color":{"r":0,"g":0,"b":0,"a":0}},"paginationHoverShadow":{"color":{"r":0,"g":0,"b":0,"a":0},"horizontal":"0","vertical":"0","blur":"0","spread":"0"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"2","right":"2","bottom":"2","left":"2"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"5"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":""}}}} -->
<div class="guten-element guten-post-list guten-qCgBEX"></div>
<!-- /wp:gutenverse/post-list -->

<!-- wp:gutenverse/button {"elementId":"guten-BvNcRR","content":"View All","buttonWidth":{"Desktop":"100"},"alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","right":"30","bottom":"18","left":"30"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"gv-color-primary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-accent-hover"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none","width":"","color":{"r":255,"g":255,"b":255,"a":1}}},"buttonBorderHover":{"radius":{"Desktop":[]},"all":{"type":"none","width":"","color":{"r":17,"g":86,"b":155,"a":1}}},"icon":"gtn gtn-right-arrow1-light","iconPosition":"after","iconSpacing":{"Desktop":"8"},"iconSize":{"Desktop":{"point":"15","unit":"px"}},"border":{"radius":{"Desktop":[]}},"borderHover":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"none"},"duration":"slow"},"color":{"type":"variable","id":"gv-color-background-tertiary"},"iconColor":{"type":"variable","id":"gv-color-background-tertiary"},"typography":{"type":"variable","id":"gv-font-button-secondary"},"hoverIconColor":{"type":"variable","id":"gv-color-background-tertiary"},"hoverTextColor":{"type":"variable","id":"gv-color-background-tertiary"},"ariaLabel":"view all blog"} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
