<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse About Vision', 'echelon-fse' ),
	'categories' => array( 'echelon-fse-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"gap":"no","elementId":"guten-el4grc","margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":"10","left":"10"}}},"zIndex":{"Desktop":"1"},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"fast"}} -->
<div class="section-wrapper" data-id="el4grc"><section class="wp-block-gutenverse-section guten-element guten-section guten-el4grc animated guten-element-hide fast desktop-fadeInDown layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-mI40lc","background":{"type":"default","color":{"type":"variable","id":"theme-3"}},"border":{"radius":{"Desktop":[]}},"boxShadow":{"color":{"r":9,"g":31,"b":52,"a":0.1},"blur":"25","vertical":"5"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"30"}},"Tablet":{"unit":"px","dimension":{"right":"0","bottom":"20"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Tablet":[]},"animation":{"type":{"Desktop":"none"},"duration":"slow"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-mI40lc slow"><div class="guten-column-wrapper" data-id="mI40lc"><!-- wp:gutenverse/icon-box {"elementId":"guten-kruekc","separateButtonLink":false,"title":"Our Vision \u0026 Mission","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim","icon":"gtn gtn-target-light","iconSize":{"Desktop":"45","Tablet":"43"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"containerBorder":{"radius":{"Desktop":[],"Mobile":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"5","bottom":"","left":""}},"Tablet":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"10","left":""}},"Tablet":[]},"iconColor":{"type":"variable","id":"theme-2"},"iconBorder":{"radius":{"Desktop":[],"Tablet":[]}},"titlePadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"10","left":""}},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"theme-0"},"titleTypography":{"type":"variable","id":"h5-font"},"descMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"theme-4"},"descTypography":{"type":"variable","id":"text-font"},"badgePadding":{"Desktop":[]},"badgeMargin":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"parentSelector":".guten-kruekc:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-kruekc guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-target-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Our Vision & Mission</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-N0Pfsp","background":{"type":"default","color":{"type":"variable","id":"theme-2"}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"30"}},"Tablet":{"unit":"px","dimension":{"left":"0","top":"","right":"","bottom":""}}},"padding":{"Desktop":[],"Tablet":[]},"animation":{"type":{"Desktop":"none"},"duration":"slow","delay":"300"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-N0Pfsp slow"><div class="guten-column-wrapper" data-id="N0Pfsp"><!-- wp:gutenverse/icon-box {"elementId":"guten-spqQLP","separateButtonLink":false,"title":"Awards \u0026 Recognition","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim","icon":"gtn gtn-medal","iconSize":{"Desktop":"45","Tablet":"43"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"containerBorder":{"radius":{"Desktop":[],"Mobile":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"5","bottom":"","left":""}},"Tablet":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"10","left":""}},"Tablet":[]},"iconColor":{"type":"variable","id":"theme-3"},"iconBorder":{"radius":{"Desktop":[],"Tablet":[]}},"titlePadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"10","left":""}},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"theme-3"},"titleTypography":{"type":"variable","id":"h5-font"},"descMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"theme-3"},"descTypography":{"type":"variable","id":"text-font"},"background":{"type":"default"},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}}},"parentSelector":".guten-spqQLP:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-spqQLP guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-medal"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Awards & Recognition</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '',
	'is_sync' => false,
);
