<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Fun Fact', 'echelon-fse' ),
	'categories' => array( 'echelon-fse-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"gap":"no","elementId":"guten-SVLM7O","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"","bottom":"120","left":""}},"Tablet":{"unit":"px","dimension":{"top":"20","bottom":"80","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"","bottom":"70"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":100},"elementId":"guten-yJDWl1","margin":{"Tablet":[]},"padding":{"Tablet":{"unit":"px","dimension":{"bottom":"10"}}}} -->
<!-- wp:gutenverse/fun-fact {"elementId":"guten-drHrCC","iconType":"none","iconBorder":{"radius":{"Desktop":[],"Tablet":[]}},"iconPadding":{"Desktop":[],"Tablet":[]},"iconMargin":{"Desktop":[],"Tablet":[]},"prefix":"","number":"1264","safeNumber":"1264","suffix":"","title":"Succesfull Project","showSupper":true,"superColor":{"type":"variable","id":"gv-color-primary"},"superTypography":{"type":"variable","id":"gv-font-fun-fact-super-font"},"superTop":{"Desktop":"10"},"superSpace":{"Desktop":"2"},"numberColor":{"Desktop":{"type":"variable","id":"gv-color-text-primary"}},"titleColor":{"Desktop":{"type":"variable","id":"gv-color-text-secondary"}},"numberTypography":{"type":"variable","id":"gv-font-fun-fact-number-font"},"titleTypography":{"type":"variable","id":"gv-font-fun-fact-title-font"},"numberBottomSpace":{"Desktop":"-5"},"titleBottomSpace":{"Desktop":""},"contentPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"imageLoad":"eager"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":null},"elementId":"guten-rkVEBK","margin":{"Tablet":[],"Mobile":[]},"padding":{"Tablet":{"unit":"px","dimension":{"bottom":"10"}},"Mobile":{"unit":"px","dimension":{"top":"10","bottom":"10"}}}} -->
<!-- wp:gutenverse/fun-fact {"elementId":"guten-8Nh3dH","iconType":"none","iconBorder":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"prefix":"","number":"47","safeNumber":"47","suffix":"","title":"Year Experience","showSupper":true,"superColor":{"type":"variable","id":"gv-color-primary"},"superTypography":{"type":"variable","id":"gv-font-fun-fact-super-font"},"superTop":{"Desktop":"10"},"superSpace":{"Desktop":"2"},"numberColor":{"Desktop":{"type":"variable","id":"gv-color-text-primary"}},"titleColor":{"Desktop":{"type":"variable","id":"gv-color-text-secondary"}},"numberTypography":{"type":"variable","id":"gv-font-fun-fact-number-font"},"titleTypography":{"type":"variable","id":"gv-font-fun-fact-title-font"},"numberBottomSpace":{"Desktop":"-5"},"titleBottomSpace":{"Desktop":""},"contentPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"margin":{"Tablet":[]},"padding":{"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"imageLoad":"eager"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":null},"elementId":"guten-3ivG2J","margin":{"Tablet":[],"Mobile":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"10"}},"Mobile":{"unit":"px","dimension":{"top":"10","bottom":"10"}}}} -->
<!-- wp:gutenverse/fun-fact {"elementId":"guten-Ho3QV8","iconType":"none","iconBorder":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"prefix":"","number":"25","safeNumber":"25","suffix":"","title":"Winning Awards","showSupper":true,"superColor":{"type":"variable","id":"gv-color-primary"},"superTypography":{"type":"variable","id":"gv-font-fun-fact-super-font"},"superTop":{"Desktop":"10"},"superSpace":{"Desktop":"2"},"numberColor":{"Desktop":{"type":"variable","id":"gv-color-text-primary"}},"titleColor":{"Desktop":{"type":"variable","id":"gv-color-text-secondary"}},"numberTypography":{"type":"variable","id":"gv-font-fun-fact-number-font"},"titleTypography":{"type":"variable","id":"gv-font-fun-fact-title-font"},"numberBottomSpace":{"Desktop":"-5"},"titleBottomSpace":{"Desktop":""},"contentPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"imageLoad":"eager"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50},"elementId":"guten-wHLY5z"} -->
<!-- wp:gutenverse/fun-fact {"elementId":"guten-7Pde8H","iconType":"none","iconBorder":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"prefix":"","number":"462","safeNumber":"462","suffix":"","title":"Satified client","showSupper":true,"superColor":{"type":"variable","id":"gv-color-primary"},"superTypography":{"type":"variable","id":"gv-font-fun-fact-super-font"},"superTop":{"Desktop":"10"},"superSpace":{"Desktop":"2"},"numberColor":{"Desktop":{"type":"variable","id":"gv-color-text-primary"}},"titleColor":{"Desktop":{"type":"variable","id":"gv-color-text-secondary"}},"numberTypography":{"type":"variable","id":"gv-font-fun-fact-number-font"},"titleTypography":{"type":"variable","id":"gv-font-fun-fact-title-font"},"numberBottomSpace":{"Desktop":"-5"},"titleBottomSpace":{"Desktop":""},"contentPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"margin":{"Tablet":[],"Mobile":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"10"}},"Mobile":{"unit":"px","dimension":{"top":"10","bottom":""}}},"imageLoad":"eager"} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
