<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse 404 Hero', 'echelon-fse' ),
	'categories' => array( 'echelon-fse-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"gap":"no","elementId":"guten-Y3fWl9","heightControl":"fit","background":{"type":"default","image":{"Desktop":{"id":1243,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/StockSnap_4FZD5QXDDN.webp"}},"position":{"Desktop":"top center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","color":{"r":0,"g":0,"b":0,"a":1}},"opacity":"0.7","margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":""}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-8odAa3","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-IlQkrv","content":"404","type":1,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"gv-color-background-tertiary"},"typography":{"type":"variable","id":"gv-font-heading-404"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-10"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"10","left":"10"}},"Mobile":[]}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-NtCSqh","content":"Page Not Found","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"gv-color-background-tertiary"},"typography":{"type":"variable","id":"gv-font-secondary"},"containsAnchorTag":false,"margin":{"Tablet":[],"Mobile":[],"Desktop":{"unit":"px","dimension":{"bottom":"60"}}},"padding":{"Tablet":{"unit":"%","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"%","dimension":{"right":"0","left":"0"}},"Desktop":[]}} /-->

<!-- wp:gutenverse/search {"elementId":"guten-Ibysaa","buttonWidth":{"Desktop":{"point":"100","unit":"px"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"placeholderColor":{"Desktop":{"type":"variable","id":"gv-color-dark-text-placeholder"}},"inputPlaceholder":"Search here...","inputPadding":{"Desktop":{"unit":"px","dimension":{"left":"14","right":"14"}}},"inputMargin":{"Desktop":[]},"inputHeight":{"Desktop":"60","Tablet":""},"inputWidth":{"Desktop":{"unit":"%","point":"60"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"inputTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"15"},"Tablet":{"unit":"px","point":"14"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"gv-color-text-primary"}},"inputBorderNormal":{"radius":{"Desktop":[]}},"inputBorderFocus":{"radius":{"Desktop":[]}},"alignContent":{"Desktop":"center"},"closeIconType":"svg"} -->
<!-- wp:gutenverse/button {"elementId":"guten-wjQAx2","role":"submit","content":"Search","buttonSize":"xs","paddingButton":{"Desktop":{"unit":"px","dimension":{"right":"26","left":"26"}},"Mobile":{"unit":"px","dimension":{"left":"22","right":"22"}}},"buttonBackground":{"color":{"type":"variable","id":"gv-color-primary"},"type":"default"},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-accent-hover"}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"10"}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"gv-color-background-tertiary"},"iconColor":{"type":"variable","id":"gv-color-background-tertiary"},"typography":{"type":"variable","id":"gv-font-button-secondary","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"unit":"px","point":"15"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"}} /-->
<!-- /wp:gutenverse/search -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
