<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Hero', 'echelon-fse' ),
	'categories' => array( 'echelon-fse-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"gap":"no","elementId":"guten-i7LG28","background":{"type":"default","image":{"Desktop":{"id":686,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/corner-office-lit-up-at-night.webp"}},"gradientColor":[{"color":"rgb(49, 207, 180)","active":false,"id":1,"offset":"0.000"},{"color":"rgba(126, 32, 207, 0)","active":true,"opacity":0,"id":2,"offset":"0.976"}],"position":{"Desktop":"custom","Tablet":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"xposition":{"Desktop":{"point":"200","unit":"px"}},"yposition":{"Desktop":{"point":"","unit":"px"}},"videoPlayOnMobile":false,"fetchPriorityHigh":false},"backgroundOverlay":{"type":"gradient","color":{"r":1,"g":1,"b":1,"a":1},"gradientColor":[{"color":"rgba(230, 241, 252, 1)","active":true,"opacity":1,"id":1,"offset":"0.241"},{"color":"rgba(0, 0, 0, 0.65)","opacity":0.65,"active":false,"id":2,"offset":"0.242"}],"gradientType":"linear","gradientAngle":"90"},"opacity":"1","topDivider":{"width":{"Desktop":""}},"margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"110","right":"","bottom":"280","left":""}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10"}}},"hideMobile":true} -->
<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":40},"elementId":"guten-xofHUS","verticalAlign":{"Desktop":"flex-start"}} -->
<!-- wp:gutenverse/image {"elementId":"guten-aWGyiQ","imgSrc":{"media":{"imageId":26,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/StockSnap_4UMSQADUEU.webp","orientation":"landscape"},"medium":{"height":300,"width":200,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/StockSnap_4UMSQADUEU.webp","orientation":"portrait"},"large":{"height":1024,"width":683,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/StockSnap_4UMSQADUEU.webp","orientation":"portrait"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/StockSnap_4UMSQADUEU.webp","height":1600,"width":1067,"orientation":"portrait"}}},"size":"full"},"altType":"original","altOriginal":"two business man on discussion","captionOriginal":"","width":{"Desktop":{"unit":"%","point":"100"},"Tablet":{"unit":"%","point":""}},"height":{"Desktop":{"point":"500","unit":"px"},"Tablet":{"point":"438","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"all":{"type":"solid","width":"20","color":{"type":"variable","id":"gv-color-background-tertiary"}}},"imageFit":{"Desktop":"cover","Tablet":"cover"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"},"border":{"radius":{"Desktop":[]}},"imageLoad":"eager"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":66.66,"Tablet":60,"Mobile":null},"elementId":"guten-qZDtto","verticalAlign":{"Desktop":"center","Tablet":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"80"}},"Tablet":{"unit":"px","dimension":{"left":"60"}},"Mobile":{"unit":"px","dimension":{"left":"0"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"left":""}}},"animation":{"type":{"Desktop":"fadeIn"},"duration":"normal","delay":"300"}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-e1TuS9","content":"We Are Echelon","color":{"type":"variable","id":"gv-color-accent"},"typography":{"type":"variable","id":"gv-font-subheading"},"containsAnchorTag":false} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-IlQkrv","content":"Smart Solutions To Grow Your Business","type":1,"color":{"type":"variable","id":"gv-color-background-tertiary"},"typography":{"type":"variable","id":"gv-font-primary"},"containsAnchorTag":false} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-zBggiI","textColor":{"type":"variable","id":"gv-color-background-tertiary"},"typography":{"type":"variable","id":"gv-font-text-hero"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"%","dimension":{"top":"0","right":"26","bottom":"0","left":"0"}},"Tablet":{"unit":"%","dimension":{"right":"1","top":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Tablet":[]}} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/button {"elementId":"guten-bHlmEG","content":"Get Started","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"16","bottom":"16","right":"28","left":"28"}},"Tablet":[]},"buttonBackground":{"type":"default","color":{"type":"variable","id":"gv-color-primary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-accent-hover"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"gv-color-background-tertiary"},"iconColor":{"type":"variable","id":"gv-color-background-tertiary"},"typography":{"type":"variable","id":"gv-font-button-primary"}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
